name: mojquiz
description: A high-performance, gamified quiz application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Backend (Firebase)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_functions: ^4.6.8
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17
  firebase_dynamic_links: ^5.4.8

  # Monetization
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.1.11

  # Utils
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
