name: mojquiz
description: A high-performance, gamified quiz application.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Navigation
  go_router: ^17.0.1

  # Backend (Firebase)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  firebase_remote_config: ^5.5.0
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_dynamic_links: ^6.1.10

  # Monetization
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.1.11

  # Utils
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^6.0.0
  cloud_functions: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - .env
